### ISSUE TITLE
joymap - data format to expend timespan ?

### ISSUE THREAD

**Issue by nicolsc** [1wheel/roadtolarissa#1]
Hi,

Really like your project. 
It would be great to visualise population data way before the 90s

How is formatted the current data file ?

**Comment by 1wheel** [comment]
Finding data for that will probably be your biggest hurdle.

What I'm using:

[raw data](http://sedac.ciesin.columbia.edu/data/set/grump-v1-population-count)
[downloaded raw data](https://github.com/1wheel/roadtolarissa/tree/master/projectPosts/joymap/rawData)
[some aggergration](https://github.com/1wheel/roadtolarissa/blob/master/projectPosts/joymap/parseData.js)
[json](https://github.com/1wheel/roadtolarissa/blob/master/projectPosts/joymap/formatedData.json)
