### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by pjpscriv** [1wheel/roadtolarissa#8]
Hi @1wheel,

It looks like the certificate for roadtolarissa.com has expired. Just had this flagged in a [StackOverflow comment](https://stackoverflow.com/questions/37320173/why-have-all-my-d3-bl-ocks-disappeared-from-bl-ocks-org/75351168?noredirect=1#comment136498765_75351168). It is giving this error on Firefox:

> "Warning: Potential Security Risk Ahead Firefox detected an issue and did not continue to blocks.roadtolarissa.com. The website is either misconfigured or your computer clock is set to the wrong time."

Here's what the certificate looks like in my browser. I'm in UTC+13:00 - New Zealand Daylight Savings time zone :)

![image](https://github.com/1wheel/roadtolarissa/assets/16329923/1e30afb4-cec5-4b01-8f19-65d96724828c)

I'm aware this is more an infra issue than a code issue, so the repo isn't the best place to flag this 😅. Let me know if there's a better place 🙂.

**Comment by 1wheel** [comment]
Fixed, sorry about that! 

I have certbot running automatically, but still need to manually run `sudo service nginx restart`; I haven't quite figured out how to that 😬.
